llm:
  provider: "openai"
  model_id: "gpt-4o"
  api_key_env: "OPENAI_API_KEY"
  max_tokens: 100

agents:
  num_agents: 3
  strategies:
    aggressive: 1
    defensive: 1
    balanced: 1

chess:
  max_moves: 2
  autosave: true
