agents:
  num_agents: 3
  strategies:
    aggressive: 1
    balanced: 1
    defensive: 1
chess:
  autosave: true
  max_moves: 50
llm:
  api_key_env: OPENAI_API_KEY
  max_tokens: 100
  model_id: gpt-4o
  provider: openai
